package com.eli.bot.constants;

/**
 * @author Eli
 */
public class VdmConstant {

    private VdmConstant() {
    }

    public static final int RECALL_TICK = 256;

    public static final String SPEC_PLAYER = "\"%s\"\n" +
            "\t{\n" +
            "\t\tfactory \"PlayCommands\"\n" +
            "\t\tname \"spec%s\"\n" +
            "\t\tstarttick \"%s\"\n" +
            "\t\tcommands \"spec_player_by_accountid %s\"\n" +
            "\t}\n";

    public static final String EXECUTE_COMMAND = "\"%s\"\n" +
            "\t{\n" +
            "\t\tfactory \"PlayCommands\"\n" +
            "\t\tname \"spec%s\"\n" +
            "\t\tstarttick \"%s\"\n" +
            "\t\tcommands \"%s\"\n" +
            "\t}\n";

    public static final String SKIP_AHEAD = "\"%s\"\n" +
            "\t{\n" +
            "\t\tfactory \"SkipAhead\"\n" +
            "\t\tname \"SkipAhead%s\"\n" +
            "\t\tstarttick \"%s\"\n" +
            "\t\tskiptotick \"%s\"\n" +
            "\t}\n";

    public static final String MAIN = "// Generated by EliBot\n" +
            "demoactions\n" +
            "{\n" +
            "\t%s\n" +
            "}";

}
